"""
    neurostore draft api

    Query dataset and meta-analyses  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.id_only import IdOnly


class TestIdOnly(unittest.TestCase):
    """IdOnly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdOnly(self):
        """Test IdOnly"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdOnly()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
