"""
    neurostore draft api

    Query dataset and meta-analyses  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_api
from neurostore_api.api.conditions_api import ConditionsApi  # noqa: E501


class TestConditionsApi(unittest.TestCase):
    """ConditionsApi unit test stubs"""

    def setUp(self):
        self.api = ConditionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_conditions_id_get(self):
        """Test case for conditions_id_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_conditions_id_put(self):
        """Test case for conditions_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
