"""
    neurostore draft api

    Query dataset and meta-analyses  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_api
from neurostore_api.api.studies_api import StudiesApi  # noqa: E501


class TestStudiesApi(unittest.TestCase):
    """StudiesApi unit test stubs"""

    def setUp(self):
        self.api = StudiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_studies_get(self):
        """Test case for studies_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_studies_id_get(self):
        """Test case for studies_id_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_studies_id_put(self):
        """Test case for studies_id_put

        """
        pass

    def test_studies_post(self):
        """Test case for studies_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
