"""
    neurostore draft api

    Query dataset and meta-analyses  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_api
from neurostore_api.api.analyses_api import AnalysesApi  # noqa: E501


class TestAnalysesApi(unittest.TestCase):
    """AnalysesApi unit test stubs"""

    def setUp(self):
        self.api = AnalysesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analyses_get(self):
        """Test case for analyses_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_analyses_id_get(self):
        """Test case for analyses_id_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_analyses_id_put(self):
        """Test case for analyses_id_put

        """
        pass

    def test_analyses_post(self):
        """Test case for analyses_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
